name: Build image and deploy
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop
    tags:
      - 'v*'

jobs:
  version-info:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    outputs:
      version: ${{ steps.set_outputs.outputs.version }}
      version_tag: ${{ steps.set_outputs.outputs.version_tag }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          activate-environment: true

      - name: set outputs
        id: set_outputs
        run: |
          export SDIST_VERSION=$(python -m setuptools_scm)
          echo "version=${SDIST_VERSION}" >> ${GITHUB_OUTPUT}
          echo "version_tag=${SDIST_VERSION/+/_}" >> ${GITHUB_OUTPUT}
          echo "Version number: ${SDIST_VERSION}"


  dockerize:
    needs: version-info
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ needs.version-info.outputs.version_tag }}
      cancel-in-progress: true
    permissions:
      contents: read
      id-token: write
    env:
      ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
      VERSION_TAG: ${{ needs.version-info.outputs.version_tag }}
      PLATFORMS: 'linux/amd64'
    outputs:
      image_uri: ${{ steps.set_outputs.outputs.IMAGE_URI }}
    steps:
      - uses: actions/checkout@v5

      - name: set env and outputs
        id: set_outputs
        run: |
          export ECR_REPOSITORY=${GITHUB_REPOSITORY,,}
          echo "ECR_REPOSITORY=${ECR_REPOSITORY}" >> ${GITHUB_ENV}
          export IMAGE_URI=${ECR_REGISTRY}/${ECR_REPOSITORY}:${VERSION_TAG}
          echo "IMAGE_URI=${IMAGE_URI}" >> ${GITHUB_ENV}
          echo "IMAGE_URI=${IMAGE_URI}" >> ${GITHUB_OUTPUT}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}

      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}


      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build
        uses: docker/build-push-action@v6
        with:
          build-args: "SETUPTOOLS_SCM_PRETEND_VERSION=${{ needs.version-info.outputs.version }}"
          push: ${{ ! github.event.pull_request.head.repo.fork }}
          platforms: ${{ env.PLATFORMS }}
          provenance: false
          tags: |
            ${{ env.IMAGE_URI }}

      - name: Add test tag
        if: ${{ github.event_name != 'pull_request' && contains(env.VERSION_TAG, '.dev') }}
        uses: akhilerm/tag-push-action@v2.2.0
        with:
          src: ${{ env.IMAGE_URI }}
          dst: ${{ vars.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:test

      - name: Add latest tag
        if: ${{ github.event_name != 'pull_request' && ! contains(env.VERSION_TAG, '.dev') }}
        uses: akhilerm/tag-push-action@v2.2.0
        with:
          src: ${{ env.IMAGE_URI }}
          dst: ${{ vars.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ vars.ECR_REGISTRY }}


  deploy:
    if: ${{ github.event_name != 'pull_request' }}
    concurrency:
      group: deploy-${{ startsWith(github.ref, 'refs/tags/v') && 'prod' || 'test' }}
    runs-on: ubuntu-latest
    needs:
      - dockerize
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Package and deploy
        shell: bash
        run: |
          aws cloudformation deploy \
            --template-file cloudformation.yml \
            --stack-name=cmr-notifier-${{ startsWith(github.ref, 'refs/tags/v') && 'prod' || 'test' }} \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              EcrImageUri=${{ needs.dockerize.outputs.image_uri }} \
              CmrDomainName=${{ vars.CMR_DOMAIN_NAME }} \
              CmrProvider=${{ vars.CMR_PROVIDER }}
