name: Static analysis

on: push

jobs:
  call-secrets-analysis-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-secrets-analysis.yml@v0.21.0
    permissions:
      contents: read

  pixi-static-tasks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        pixi_task:
          - lint-cf
          - "ruff check --output-format=github"
          - "ruff format --diff"
          - type-py
    steps:
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.3
      - run: |
          pixi run ${{ matrix.pixi_task }}
